version: "3.4"
services:
  mongo:
    image: mongo:3.6
    volumes:
      - dbdata:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - API_URL
      - MONGO_URL
      - PORT
      - SESSION_SECRET
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - S3_BUCKET
      - AWS_REGION
      - GITHUB_ID
      - GITHUB_SECRET
      - MAILGUN_DOMAIN
      - MAILGUN_KEY
      - EMAIL_SENDER
      - EMAIL_VERIFY_SECRET_TOKEN
      - S3_BUCKET_URL_BASE
      - GG_EXAMPLES_USERNAME
      - GG_EXAMPLES_PASS
      - GG_EXAMPLES_EMAIL
      - GOOGLE_ID
      - GOOGLE_SECRET
      - EXAMPLE_USER_EMAIL
      - EXAMPLE_USER_PASSWORD
      - ML5_EXAMPLES_USERNAME
      - ML5_EXAMPLES_PASS
      - ML5_EXAMPLES_EMAIL
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mongo
volumes:
  dbdata:
